"""Add events and point_transactions tables

Revision ID: 0744713e6dd3
Revises: fed0db1dbc5e
Create Date: 2025-09-21 13:55:57.590934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0744713e6dd3'
down_revision: Union[str, Sequence[str], None] = 'fed0db1dbc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
