"""update events table

Revision ID: 7e08677e99ea
Revises: e381cd8beda2
Create Date: 2025-09-30 15:11:13.323428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e08677e99ea'
down_revision: Union[str, Sequence[str], None] = 'e381cd8beda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(), nullable=False))
    op.add_column('events', sa.Column('category', sa.String(), nullable=True))
    op.add_column('events', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('participation_points', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('winner_points', sa.Integer(), nullable=True))
    op.drop_column('events', 'name')
    op.drop_column('events', 'points_awarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('points_awarded', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'winner_points')
    op.drop_column('events', 'participation_points')
    op.drop_column('events', 'date')
    op.drop_column('events', 'category')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
