"""Add wins column to student_total

Revision ID: b87608f7d6b6
Revises: e25c51c1dfd5
Create Date: 2025-10-23 20:53:35.851993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87608f7d6b6'
down_revision: Union[str, Sequence[str], None] = 'e25c51c1dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_totals', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_totals', 'wins')
    # ### end Alembic commands ###
