"""Add users table

Revision ID: b8a314bfdf7b
Revises: da28772d49af
Create Date: 2025-09-21 16:02:59.811532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8a314bfdf7b'
down_revision: Union[str, Sequence[str], None] = 'da28772d49af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('points_awarded', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_column('events', 'title')
    op.drop_column('events', 'category')
    op.drop_column('events', 'participation_points')
    op.drop_column('events', 'winner_points')
    op.drop_column('events', 'date')
    op.add_column('point_transactions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('point_transactions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_transactions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('point_transactions', 'timestamp')
    op.add_column('events', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('winner_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('participation_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.drop_column('events', 'points_awarded')
    op.drop_column('events', 'description')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
