"""Add created_at column to students

Revision ID: e25c51c1dfd5
Revises: dae99fc7d581
Create Date: 2025-10-23 20:48:57.046112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25c51c1dfd5'
down_revision: Union[str, Sequence[str], None] = 'dae99fc7d581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
